# version: '3.8'
services:
  web1:
    build: ./src
    ports:
      - "5000:5000"
    volumes:
      - ./src:/src
    environment:
      SERVER_ID: SERVER-1

  web2:
    build: ./src
    ports:
      - "8080:5000"
    volumes:
      - ./src:/src
    environment:
      SERVER_ID: SERVER-2
      
  nginx:
    image: nginx:latest
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2