from dao import MoleculeDAO

# z = MoleculeDAO.create(smiles='GUESS')
# print(z)

# v = MoleculeDAO.get(id=200)
# y = MoleculeDAO.create(id=7, smiles='Givenchi')
# z = MoleculeDAO.create(id=7, smiles='F')
# print(MoleculeDAO.delete(7))
# s = MoleculeDAO.get(id=2)
# print(type(s), s)
s = MoleculeDAO.all()
print(type(s), s)
# for x in s:
#     print(type(x), x)
l = MoleculeDAO.last(smiles='Chu')
print('last', l)
# MoleculeDAO.insert('Louis', 'Viton', 'Chu')

# print(MoleculeDAO.filter(smiles='y'))
# print(MoleculeDAO.get(id=3, smiles='y'))
MoleculeDAO.update(id=32, smiles='Hermes')
# print(MoleculeDAO.get(smiles='Yeah'))
print(MoleculeDAO.all(5))
print(MoleculeDAO.all(5, 5))
print(MoleculeDAO.all(offset=10))
print(MoleculeDAO.smiles())
print(MoleculeDAO.smiles(7, 20))
s = MoleculeDAO.get(id=27)
print(s.id, s.smiles)
