# Environment build stage
FROM continuumio/miniconda3 AS build
RUN conda install -c conda-forge  --yes conda-pack

# Create the conda environment using environment.yml file
COPY environment.yml .
RUN conda env create -f environment.yml \
    && find /opt/conda/ -follow -type f -name '*.a' -delete \
    && find /opt/conda/ -follow -type f -name '*.pyc' -delete \
    && find /opt/conda/ -follow -type f -name '*.js.map' -delete \
    && find /opt/conda/lib/python*/site-packages/bokeh/server/static -follow -type f -name '*.js' ! -name '*.min.js' -delete

# Package the environment as tar using conda-pack
RUN conda-pack -n slim -o /tmp/env.tar && \
  mkdir /venv && cd /venv && tar -xf /tmp/env.tar && \
  rm /tmp/env.tar
# RUN conda-pack -n slim -o /tmp/env.tar 
# WORKDIR /venv 
# RUN tar -xf /tmp/env.tar && \
  rm /tmp/env.tar
RUN /venv/bin/conda-unpack


# Runtime stage

# using slim debian image as the base image for the environment
FROM debian:12.6-slim AS runtime

# Copy the environment directory from the build stage
COPY --from=build /venv /venv

# test if the image has packages properly installed
SHELL ["/bin/bash", "-c"]
ENTRYPOINT source /venv/bin/activate && \
           uvicorn --version && \
           pip list "
