name: Python cloud deployment

on:
  pull_request:
    types:
      - closed
    branches:
      - deploy
  push:
    branches: [ "boto3-lambda" ]

permissions:
  contents: read

jobs:
  implement_deployment:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install boto3
    - name: Deploy to cloud
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        NEW_EC2_INSTANCE: ${{ secrets.NEW_EC2_INSTANCE }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      run: |
        python extra/cloud_deployment.py
