name: Run tests workflow

on: 
  push:
    branches:
      - workflow
  pull_request:
    branches: [main,develop]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt && |
          python -m pip install -r tests/pytest_requirements.txt
      - name: Test with pytest
        run: |
          pytest tests -v
